# Webcam overlay for screen recording
windowrule = float on, match:class my.org.webcam
windowrule = pin on, match:class my.org.webcam
windowrule = no_initial_focus on, match:class my.org.webcam
windowrule = no_dim on, match:class my.org.webcam
windowrule = size 243 136, match:class my.org.webcam
windowrule = opacity 1 1, match:class my.org.webcam
windowrule = border_size 0, match:class my.org.webcam
windowrule = move (monitor_w-247) (monitor_h*0.04), match:class my.org.webcam
