# Webcam overlay for screen recording
windowrule = float on, match:class my.org.webcam
windowrule = pin on, match:class my.org.webcam
windowrule = no_initial_focus on, match:class my.org.webcam
windowrule = no_dim on, match:class my.org.webcam
windowrule = move (monitor_w-window_w-6) 36, match:class my.org.webcam
windowrule = size 243 136, match:class my.org.webcam
