[colors-dark]
# Dracula
cursor=282a36 f8f8f2
foreground=f8f8f2
background=282a36

# ANSI
regular0=282a36
regular1=ff5555
regular2=50fa7b
regular3=f1fa8c
regular4=bd93f9
regular5=ff79c6
regular6=8be9fd
regular7=f8f8f2

bright0=4d5066
bright1=ff6e6e
bright2=69ff94
bright3=ffffa5
bright4=d6acff
bright5=ff92df
bright6=a4ffff
bright7=ffffff

# Extended colors
16=ffb86c
17=bd93f9

# Selection
selection-foreground=f8f8f2
selection-background=4d5066

# Search
search-box-no-match=282a36 ff5555
search-box-match=f8f8f2 4d5066

# Jump labels
jump-labels=282a36 ffb86c

# URLs
urls=8be9fd
