#!/usr/bin/env bash
OUTPUT_DIR="$HOME/Pictures/Screenshots"
mkdir -p "$OUTPUT_DIR"
MODE="${1:-region}"
TIMESTAMP="$(date +'%Y-%m-%d_%H-%M-%S')"

case "$MODE" in
  fullscreen)
    sleep 0.2
    grim - | \
      satty --filename - \
        --output-filename "$OUTPUT_DIR/screenshot-$TIMESTAMP.png" \
        --early-exit \
        --copy-command 'wl-copy'
    ;;
  region|*)
    sleep 0.2
    grim -g "$(slurp)" - | \
      satty --filename - \
        --output-filename "$OUTPUT_DIR/screenshot-$TIMESTAMP.png" \
        --early-exit \
        --copy-command 'wl-copy'
    ;;
esac
