#!/usr/bin/env bash

set -e

if [[ $# -lt 1 ]]; then
  echo "Usage: my-hook [name] [args...]"
  exit 1
fi

HOOK="$1"
HOOK_PATH="$HOME/.config/hooks/$HOOK"
shift

if [[ -f "$HOOK_PATH" ]]; then
  bash "$HOOK_PATH" "$@"
fi
