#!/usr/bin/env bash

BINDINGS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/mango/bindings.txt"

if [[ ! -f "$BINDINGS_FILE" ]]; then
    notify-send "Error" "bindings.txt not found!" -u critical
    exit 1
fi

grep -v '^#' "$BINDINGS_FILE" | grep -v '^\s*$' | \
    my-launch-fuzzel dmenu --width 70 --lines 10

exit 0
