#!/usr/bin/env bash

command -v tte >/dev/null || exit 1

pgrep -f org.screensaver >/dev/null && exit 0

if [[ -f ~/.local/state/my/toggles/screensaver-off ]] && [[ "$1" != "force" ]]; then
  exit 1
fi

pkill -f org.screensaver 2>/dev/null

nohup kitty --class=org.screensaver \
  --override font_size=18 \
  --override window_padding_width=0 \
  -e my-cmd-screensaver >/dev/null 2>&1 &
