#!/usr/bin/env bash

if command -v brave-browser &> /dev/null; then
  browser_exec="brave-browser"
elif command -v brave &> /dev/null; then
  browser_exec="brave"
else
  echo "Brave not found"
  exit 1
fi

exec $browser_exec --app="$1" "${@:2}"
