#!/usr/bin/env bash
#
set -euo pipefail
EMOJI="$(fuzzel --dmenu --placeholder "Search emoji " --lines 10 --width 60 < ~/.local/share/emoji.txt | cut -d ' ' -f 1 | tr -d '\n')"
wtype "$EMOJI"; wl-copy "$EMOJI"
