#!/usr/bin/env bash
BG_PATH="$1"
CURRENT_BACKGROUND_LINK="$HOME/.config/theme/current/background"
[[ -z "$BG_PATH" ]] && exit 1
# Update symlink
ln -nsf "$BG_PATH" "$CURRENT_BACKGROUND_LINK"
REAL_PATH="$(readlink -f "$CURRENT_BACKGROUND_LINK")"
# Set wallpaper dengan swaybg
pkill swaybg 2>/dev/null || true
swaybg -i "$REAL_PATH" -m fill &
notify-send "Background changed" "$(basename "$REAL_PATH")" -t 2000
