#!/usr/bin/env bash
ON_TEMP=4000

restart_nightlighted_waybar() {
  if grep -q "custom/nightlight" ~/.config/waybar/config.jsonc; then
    my-restart-waybar
  fi
}

if pgrep -x wlsunset >/dev/null; then
  pkill -x wlsunset
  notify-send "  Daylight screen temperature"
else
  setsid wlsunset -t "$ON_TEMP" -T "$((ON_TEMP + 1))" -l 90 -L 0 >/dev/null 2>&1 &
  notify-send "  Nightlight screen temperature"
fi

restart_nightlighted_waybar
