#!/usr/bin/env bash

CURRENT_LAYOUT=$(hyprctl getoption general:layout -j | jq -r '.str')

if [ "$CURRENT_LAYOUT" = "dwindle" ]; then
    hyprctl keyword general:layout "scrolling"
    notify-send "Layout Changed" "Scrolling"
else
    hyprctl keyword general:layout "dwindle"
    notify-send "Layout Changed" "Dwindle"
fi
