#!/usr/bin/env bash

BACKGROUNDS_DIR="$HOME/.config/theme/backgrounds"
CURRENT_BACKGROUND_LINK="$HOME/.config/theme/current/background"

mapfile -d '' -t BACKGROUNDS < <(
  find -L "$BACKGROUNDS_DIR" -type f -print0 | sort -z
)

TOTAL=${#BACKGROUNDS[@]}

if [[ "$TOTAL" -eq 0 ]]; then
  notify-send "No background was found for theme" -t 2000
  pkill swaybg
  swaybg --color '#000000' &
  exit 0
fi

if [[ -L "$CURRENT_BACKGROUND_LINK" ]]; then
  CURRENT_BACKGROUND="$(readlink -f "$CURRENT_BACKGROUND_LINK")"
else
  CURRENT_BACKGROUND=""
fi

INDEX=-1
for i in "${!BACKGROUNDS[@]}"; do
  if [[ "$(basename "${BACKGROUNDS[$i]}")" == "$(basename "$CURRENT_BACKGROUND")" ]]; then
    INDEX=$i
    break
  fi
done

if [[ "$INDEX" -eq -1 ]]; then
  NEW_BACKGROUND="${BACKGROUNDS[0]}"
else
  NEXT_INDEX=$(((INDEX + 1) % TOTAL))
  NEW_BACKGROUND="${BACKGROUNDS[$NEXT_INDEX]}"
fi

ln -nsf "$NEW_BACKGROUND" "$CURRENT_BACKGROUND_LINK"

pkill swaybg
sleep 0.2
swaybg -i "$(readlink -f "$CURRENT_BACKGROUND_LINK")" -m fill &
