#!/usr/bin/env bash

ON_TEMP=4000
OFF_TEMP=6000

# Ensure hyprsunset is running
if ! pgrep -x hyprsunset >/dev/null; then
  setsid hyprsunset >/dev/null 2>&1 &
  sleep 1
fi

CURRENT_TEMP=$(hyprctl hyprsunset temperature 2>/dev/null | grep -oE '[0-9]+')

restart_nightlighted_waybar() {
  if grep -q "custom/nightlight" ~/.config/waybar/config.jsonc; then
    my-restart-waybar
  fi
}

if [[ "$CURRENT_TEMP" == "$OFF_TEMP" ]]; then
  hyprctl hyprsunset temperature "$ON_TEMP"
  notify-send "  Nightlight screen temperature"
else
  hyprctl hyprsunset temperature "$OFF_TEMP"
  notify-send "  Daylight screen temperature"
fi

restart_nightlighted_waybar
