#!/usr/bin/env bash

if [[ -z "$1" || "$1" == "CNCLD" ]]; then
  echo "Usage: my-theme-set <theme-name>"
  exit 1
fi

THEMES_DIR="$HOME/.config/theme/themes"
CURRENT_THEME_DIR="$HOME/.config/theme/current/theme"

THEME_NAME=$(echo "$1" |
  sed -E 's/<[^>]+>//g' |
  tr '[:upper:]' '[:lower:]' |
  tr ' ' '-')

THEME_PATH="$THEMES_DIR/$THEME_NAME"

if [[ ! -d "$THEME_PATH" ]]; then
  echo "Theme '$THEME_NAME' does not exist in $THEMES_DIR"
  exit 1
fi

ln -nsf "$THEME_PATH" "$CURRENT_THEME_DIR"

if [[ -f "$CURRENT_THEME_DIR/btop.theme" ]]; then
  ln -nsf "$CURRENT_THEME_DIR/btop.theme" \
    "$HOME/.config/btop/themes/current.theme"
fi

# Reload components
pgrep -x waybar >/dev/null && my-restart-waybar
my-restart-swayosd
my-restart-terminal
hyprctl reload
pkill -SIGUSR2 btop 2>/dev/null || true
makoctl reload

# Theme integrations
my-theme-set-gnome
my-theme-set-browser
my-theme-set-vscode

my-hook theme-set "$THEME_NAME"
