#!/usr/bin/env bash

if [[ -z "$1" || "$1" == "CNCLD" ]]; then
    echo "Usage: my-theme-set <theme-name>"
    exit 1
fi

THEMES_DIR="$HOME/.config/theme/themes"
CURRENT_THEME_DIR="$HOME/.config/theme/current/theme"
THEME_NAME=$(echo "$1" |
    sed -E 's/<[^>]+>//g' |
    tr '[:upper:]' '[:lower:]' |
    tr ' ' '-')
THEME_PATH="$THEMES_DIR/$THEME_NAME"

if [[ ! -d "$THEME_PATH" ]]; then
    echo "Theme '$THEME_NAME' does not exist in $THEMES_DIR"
    exit 1
fi

ln -nsf "$THEME_PATH" "$CURRENT_THEME_DIR"

# reload mangowm
mmsg dispatch reload_config
# reload quickshell 
quickshell ipc call island reloadTheme
# reload kitty
pkill -SIGUSR1 kitty 2>/dev/null || true
# reload btop
pkill -SIGUSR2 btop 2>/dev/null || true
# reload mako
makoctl reload
# reload tmux
tmux source-file "$CURRENT_THEME_DIR/tmux.conf" 2>/dev/null || true 
# reload nvim
if pgrep -x nvim >/dev/null; then
    for socket in /tmp/nvim*/0 $XDG_RUNTIME_DIR/nvim.*; do
        if [ -S "$socket" ]; then
            nvim --server "$socket" --remote-send "<Cmd>lua dofile(vim.fn.expand('~/.config/theme/current/theme/nvim.lua'))<CR>" 2>/dev/null || true
        fi
    done
fi
# reload vscode
VSCODE_CONF="$HOME/.config/Code/User/settings.json"

if [[ -f "$CURRENT_THEME_DIR/vscode.json" && -f "$VSCODE_CONF" ]]; then
    NEW_VS_THEME=$(jq -r '."workbench.colorTheme"' "$CURRENT_THEME_DIR/vscode.json")
    if [[ -n "$NEW_VS_THEME" && "$NEW_VS_THEME" != "null" ]]; then
        tmp_json=$(mktemp)
        jq --arg theme "$NEW_VS_THEME" '."workbench.colorTheme" = $theme' "$VSCODE_CONF" > "$tmp_json" && mv "$tmp_json" "$VSCODE_CONF"
    fi
fi

ZED_CONF="$HOME/.config/zed/settings.json"

if [[ -f "$CURRENT_THEME_DIR/zed.json" && -f "$ZED_CONF" ]]; then
    NEW_ZED_THEME=$(jq -r '."theme"' "$CURRENT_THEME_DIR/zed.json" 2>/dev/null)
    
    if [[ -n "$NEW_ZED_THEME" && "$NEW_ZED_THEME" != "null" ]]; then
        # Abaikan baris komentar // dan ganti nilai setelah "theme": "
        sed -i -E "/^[[:space:]]*\/\//b; s/(\"theme\"[[:space:]]*:[[:space:]]*\")[^\"]*/\1$NEW_ZED_THEME/" "$ZED_CONF"
    fi
fi

my-hook theme-set "$THEME_NAME"


