#!/usr/bin/env bash

CLIENT_IDS=$(mmsg get all-clients | jq -r '.clients[].id')
for id in $CLIENT_IDS; do
    if [[ -n "$id" && "$id" != "null" ]]; then
        mmsg dispatch killclient client,$id
    fi
done

