#!/usr/bin/env bash

# Ambil semua client IDs
CLIENT_IDS=$(mmsg get all-clients | jq -r '.[].id')

for id in $CLIENT_IDS; do
    if [[ -n "$id" ]]; then
        # Fokus ke window tersebut dulu
        mmsg dispatch focusid client,$id
        # Lalu kill
        mmsg dispatch killclient
    fi
done
