# Application bindings
$terminal = kitty
$browser = my-launch-browser
$editor = zeditor
$file-manager = thunar

bindd = SUPER, RETURN, Terminal, exec, $terminal
bindd = SUPER SHIFT, F, File manager, exec, my-launch-or-focus $file-manager
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, E, Editor, exec, $editor
bindd = SUPER SHIFT, T, System Dashboard, exec, my-launch-or-focus-tui btop
bindd = SUPER ALT, T, System Processes, exec, my-launch-or-focus-tui htop
bindd = SUPER SHIFT, D, Docker, exec, my-launch-or-focus-tui lazydocker
bindd = SUPER SHIFT, A, About, exec, my-launch-about
bindd = SUPER ALT, D, Disk Usage, exec, my-launch-or-focus-tui ncdu
bindd = SUPER CTRL, W, Webcam Overlay, exec, my-webcam
bindd = SUPER SHIFT, M, Email Client, exec, geary
bindd = SUPER ALT, L, Change Layout, exec, my-toggle-layout

bindeld = ,XF86Display, Display Setting, exec, my-launch-or-focus nwg-displays
bindeld = ,XF86WLAN, File Manager, exec, my-launch-or-focus $file-manager
bindeld = ,XF86NotificationCenter, DbGate, exec, my-launch-or-focus dbgate
bindeld = ,XF86PickupPhone, Bruno, exec, my-launch-or-focus bruno
bindeld = ,XF86HangupPhone, Browser, exec, $browser
bindeld = ,XF86Favorites, Editor, exec, $editor
