[colors-dark]
# Nord
cursor=2e3440 eceff4
foreground=eceff4
background=2e3440

# ANSI
regular0=2e3440
regular1=bf616a
regular2=a3be8c
regular3=ebcb8b
regular4=5e81ac
regular5=b48ead
regular6=8fbcbb
regular7=e5e9f0

bright0=444c5e
bright1=bf616a
bright2=a3be8c
bright3=ebcb8b
bright4=5e81ac
bright5=b48ead
bright6=8fbcbb
bright7=eceff4

# Extended colors
16=d08770
17=88c0d0

# Selection
selection-foreground=eceff4
selection-background=444c5e

# Search
search-box-no-match=2e3440 bf616a
search-box-match=eceff4 444c5e

# Jump labels
jump-labels=2e3440 d08770

# URLs
urls=88c0d0
