# Nord theme colors
thm_bg="#2E3440"        # nord0
thm_fg="#D8DEE9"        # nord4
thm_cyan="#88C0D0"      # nord8
thm_gray="#3B4252"      # nord1
thm_magenta="#B48EAD"   # nord15
thm_blue="#81A1C1"      # nord9
thm_black4="#434C5E"    # nord2

# Status bar
set -g status on
set -g status-position top
set -g status-bg "$thm_bg"
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100

# Messages
set -g message-style "fg=$thm_cyan,bg=$thm_gray,align=centre"
set -g message-command-style "fg=$thm_cyan,bg=$thm_gray,align=centre"

# Panes
set -g pane-border-style "fg=$thm_gray"
set -g pane-active-border-style "fg=$thm_blue"

# Windows
set -g window-status-activity-style "fg=$thm_fg,bg=$thm_bg,none"
set -g window-status-separator ""
set -g window-status-style "fg=$thm_fg,bg=$thm_bg,none"

# Current window
set -g window-status-current-format "#[fg=$thm_blue,bg=$thm_bg] #I: #[fg=$thm_magenta,bg=$thm_bg]󰄵 #[fg=$thm_cyan,bg=$thm_bg]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev)"

# Other windows
set -g window-status-format "#[fg=$thm_blue,bg=$thm_bg] #I: #[fg=$thm_fg,bg=$thm_bg]#W"

# Right status
set -g status-right "#[fg=$thm_blue,bg=$thm_bg]█#[fg=$thm_bg,bg=$thm_blue] #[fg=$thm_fg,bg=$thm_gray] #W #{?client_prefix,#[fg=$thm_magenta],#[fg=$thm_cyan]}#[bg=$thm_gray]█#{?client_prefix,#[bg=$thm_magenta],#[bg=$thm_cyan]}#[fg=$thm_bg] #[fg=$thm_fg,bg=$thm_gray] #S "

set -g status-left ""

# Modes
set -g clock-mode-colour "$thm_blue"
set -g mode-style "fg=$thm_blue bg=$thm_black4 bold"
