[colors-dark]
# Gruvbox Dark
cursor=282828 fbf1c7
foreground=fbf1c7
background=282828

# ANSI
regular0=282828
regular1=fb4934
regular2=b8bb26
regular3=fabd2f
regular4=83a598
regular5=d3869b
regular6=8ec07c
regular7=fbf1c7

bright0=474240
bright1=fb4934
bright2=b8bb26
bright3=fabd2f
bright4=83a598
bright5=d3869b
bright6=8ec07c
bright7=ffffff

# Extended colors
16=fe8019
17=d79921

# Selection
selection-foreground=fbf1c7
selection-background=474240

# Search
search-box-no-match=282828 fb4934
search-box-match=fbf1c7 474240

# Jump labels
jump-labels=282828 fe8019

# URLs
urls=83a598
