{ ... }:
{
  home.sessionVariables = {
    EDITOR = "zeditor";
    NIXOS_OZONE_WL = "1";
    MOZ_ENABLE_WAYLAND = "1";
    ELECTRON_OZONE_PLATFORM_HINT = "auto";
    QT_AUTO_SCREEN_SCALE_FACTOR = "0";
    QT_ENABLE_HIGHDPI_SCALING = "0";
    QT_SCALE_FACTOR = "1";
    GUM_CONFIRM_PROMPT_FOREGROUND = "6";
    GUM_CONFIRM_SELECTED_FOREGROUND = "0";
    GUM_CONFIRM_SELECTED_BACKGROUND = "2";
    GUM_CONFIRM_UNSELECTED_FOREGROUND = "0";
    GUM_CONFIRM_UNSELECTED_BACKGROUND = "8";
  };
}
