{ ... }:
{
  home.sessionVariables = {
    EDITOR = "zeditor";

    NIXOS_OZONE_WL = "1";
    ELECTRON_OZONE_PLATFORM_HINT = "auto";
    QT_QPA_PLATFORM = "wayland;xcb";
    
    XDG_SESSION_TYPE = "wayland";
    XDG_CURRENT_DESKTOP = "wlroots";

    GUM_CONFIRM_PROMPT_FOREGROUND = "6";
    GUM_CONFIRM_SELECTED_FOREGROUND = "0";
    GUM_CONFIRM_SELECTED_BACKGROUND = "2";
    GUM_CONFIRM_UNSELECTED_FOREGROUND = "0";
    GUM_CONFIRM_UNSELECTED_BACKGROUND = "8";
  };
}
