# --- Animations ---
animations=1
layer_animations=1

# Animation Types
animation_type_open=fade
animation_type_close=fade
layer_animation_type_open=fade
layer_animation_type_close=fade

# Fade Settings
animation_fade_in=1
animation_fade_out=1
fadein_begin_opacity=0.0
fadeout_begin_opacity=1.0

# Durations 
animation_duration_open=150
animation_duration_close=120
animation_duration_move=150
animation_duration_tag=150
animation_duration_focus=0

# Custom Bezier Curves 
animation_curve_open=0.46,1.0,0.29,0.99
animation_curve_close=0.46,1.0,0.29,0.99
animation_curve_move=0.46,1.0,0.29,0.99
animation_curve_tag=0.46,1.0,0.29,0.99
animation_curve_focus=0.46,1.0,0.29,0.99
animation_curve_opafadein=0.46,1.0,0.29,0.99
animation_curve_opafadeout=0.46,1.0,0.29,0.99

# Tag Animation Direction
tag_animation_direction=1
