# source configuration
source=./animations.conf
source=./appearance.conf
source=./bind.conf
source=./input.conf
source=./layout.conf
source=./misc.conf
source=./monitor.conf
source=./rule.conf
source=./tag.conf

# run autostart
exec-once=~/.config/mango/autostart.sh

