# keyboard
repeat_rate=50
repeat_delay=300
numlockon=1
xkb_rules_layout=us

# trackpad
trackpad_natural_scrolling=1
trackpad_scroll_factor=1.2
trackpad_accel_speed=0.2
trackpad_click_method=2
swipe_min_threshold=5

