# Laptop display (eDP-1) - Focus at startup
monitorrule=name:^eDP-1$,width:1920,height:1080,refresh:60.05,x:1471,y:1045,scale:1.25

# External Display 1 (DP-2)
monitorrule=name:^DP-2$,width:1366,height:768,refresh:59.79,x:3007,y:1141,scale:1.0

# External Display 2 (HDMI-A-1)
monitorrule=name:^HDMI-A-1$,width:1600,height:900,refresh:60.0,x:3007,y:1009,scale:1.0
