# Browser
windowrule=allow_csd:0,appid:^(google-)?[cC]hrom(e|ium)$|^brave-browser$|^microsoft-edge$|^vivaldi-stable$|^helium$|^firefox$|^zen$|^librewolf$

# Specific PWAs (YouTube, Zoom Web)
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:^chrome-youtube\.com__-Default$|^chrome-app\.zoom\.us__wc_home-Default$

# Clock App (Floating & Fixed Size)
windowrule=isfloating:1,width:480,height:200,appid:^org\.my\.clock-rs$

# Sharing Apps (LocalSend, etc.)
windowrule=isfloating:1,appid:^(Share|localsend_app)$

# Picture-in-Picture (PiP)
windowrule=isglobal:1,isfloating:1,isopensilent:1,width:504,height:284,focused_opacity:1.0,unfocused_opacity:1.0,title:(?i)picture.?in.?picture

# Webcam Overlay
windowrule=isfloating:1,isopensilent:1,width:380,height:240,focused_opacity:1.0,unfocused_opacity:1.0,appid:^my\.org\.webcam$

# CShift Utility
windowrule=isfloating:1,width:620,height:370,appid:^org\.my\.cshift$

# Kitty Terminal (Transparency)
windowrule=focused_opacity:0.9,unfocused_opacity:0.9,appid:^kitty$

# Media Apps (No Transparency for better performance/visuals)
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:^zoom$|^vlc$|^mpv$|^org\.kde\.kdenlive$|^com\.obsproject\.Studio$|^com\.github\.PintaProject\.Pinta$|^imv$

# General TUIs & Utilities (Btop, Ncdu, Htop, etc.)
windowrule=isfloating:1,width:875,height:600,appid:^org\.my\.bluetui$|^org\.my\.impala$|^org\.my\.wiremix$|^org\.my\.btop$|^org\.my\.terminal$|^com\.gabm\.satty$|^TUI\.float$|^imv$|^mpv$|^org\.my\.calcure$|^org\.my\.ncdu$|^org\.my\.htop$|^org\.my\.bash$|^org\.my\.termusic$

# About
windowrule=isfloating:1,width:960,height:480,appid:^org\.my\.about$

# File Picker Dialogs (GTK/Sublime)
windowrule=isfloating:1,width:875,height:600,appid:^xdg-desktop-portal-gtk$|^sublime_text$|^DesktopEditors$

# Title-based Matching for Save/Open Dialogs
windowrule=isfloating:1,width:875,height:600,title:^(Open.*Files?|Open [Ff]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to (open|save).*|[Cc]hoose.*|.*Login - Akun Google.*)

# GNOME Calculator
windowrule=isfloating:1,appid:^org\.gnome\.Calculator$

# Thunar Rename Dialog
windowrule=isfloating:1,width:480,height:160,title:^Rename.*
